BoxLayout:
    synth: 'test_synth'
    orientation: 'vertical'
    DropDownController:
        nrpn: 5
        option_list: 'destinations'
        Option:
            name: 'BPM'
            midi_minimum: 3
            midi_maximum: 53
    SwipeController:
        name: 'swipe'
        nrpn: 5
        offset: -97
        minimum: 100
        maximum: 150
    HSlideController:
        name: 'slide'
        notes: True

    DropDownController:
        list_offset: 51
        nrpn: 6
        option_list: 'destinations'
        Option:
            name: 'BPM'
            midi_minimum: 0
            midi_maximum: 50
            
    SwipeController:
        name: 'swipe'
        nrpn: 6
        minimum: 100
        maximum: 150
        offset: -100
    
    
    RadioController:
        group: 'g1'
        nrpn: 2
        BoxLayout:
            orientation: 'vertical'
            RadioButton:
                text: '0'
                midi_value: 0
            RadioButton:
                text: '1'
                midi_value: 1
            RadioButton:
                text: '2'
                midi_value: 2
            RadioButton:
                text: '3'
                midi_value: 3
            RadioButton:
                text: '4-103'
                midi_minimum: 4
                midi_maximum: 103
                
    SwipeController:
        nrpn: 2
        minimum: 0
        maximum: 99
        offset: 4
    TestController:
        id: tester
        Button:
            on_press: tester.run_test()
    

    
    
